### ISSUE TITLE
Cant reload weapon

### ISSUE THREAD

**Issue by kellengg02** [thelindat/hsn-inventory#10]
I cant reload the weapon. I used the command to give item pistol and ammo and then I uses the bullets but nothing happen.

**Comment by thelindat** [comment]
Any errors coming through the server console? Also, from the video you posted it seemed your inventory wasn't opening up either (but doing the animation), is that the case?

**Comment by kellengg02** [comment]
I re-download the script today and did a clean install and thats problem was resolved until now. But Im having a bug, if you get out of ammo, the weapon is withdrawn. But if you withdraw the weapon in next time you will have ammo again one more time. Like you have 12 bullets and spend them all, the weapon is withdrawn, 0 bullets in inventory, you withdraw the weapon and will have again the 12 bullets, but this just happens one time.

**Comment by thelindat** [comment]
Was able to replicate the issue, implementing a fix soon.

**Comment by thelindat** [comment]
Resolved in latest commit.
