### ISSUE TITLE
Shops

### ISSUE THREAD

**Issue by BryanLTU** [thelindat/hsn-inventory#13]
So I don't know if I'm the only one who had these issues:

1. When you buy something from shop, in shop inventory the same item will change it's price to his weight. And then you can't buy same item.
2. When you buy item for which you don't have enough money, it will still appear in your inventory. What you need is just re-open it and it will be fine. But when that item is dragged to another slot in your inventory, it gets stuck. You can't use it.

**Comment by thelindat** [comment]
Known issues, but good to have them listed on the repo.

I've put in some fixes for the 2nd issue, but the javascript needs a fair bit of work done regarding stacking and swapping items.

**Comment by BryanLTU** [comment]
I really appreciate what you're doing. Hoping for the best!

**Comment by thelindat** [comment]
No longer issues in more recent versions.
