### ISSUE TITLE
Items List Error

### ISSUE THREAD

**Issue by LordTiger** [thelindat/hsn-inventory#15]
SCRIPT ERROR: @hsn-inventory/server.lua:38: attempt to index a nil value (global 'Config')
> ref (@hsn-inventory/server.lua:38)
>  (@ghmattimysql/ghmattimysql-server.js:1)

**Comment by thelindat** [comment]
Unsure what's causing a nil value here.

Is everything else loading properly (framework, ghmattimysql)?
Correct load order (hsn-inventory shouldn't load until sometime after both)?

**Comment by LordTiger** [comment]
yea i just redownloaded it, seems its working now
