### ISSUE TITLE
lockpick use

### ISSUE THREAD

**Issue by Johnny-Probably** [thelindat/hsn-inventory#20]
When using this with nui_doorlock and esx_lockpick. The progress bar completes but the doors did not unlock. Checking F8 showed message
getnetworkobject no object by id 0

Removing lockpick from the hsn-inventory config and client.lua made the pick lock/unlock doors but this was not ideal.

**Comment by thelindat** [comment]
https://github.com/thelindat/hsn-inventory/commit/ad2a7c6e4e3d13522023f28498ca14761b3c034c
