### ISSUE TITLE
No Export for 'openTargetInventory'

### ISSUE THREAD

**Issue by LordTiger** [thelindat/hsn-inventory#25]
I putted it in there for you, 

ooh and sometimes you cant pickup other players items if they drop them

fx_version 'adamant'
game 'gta5'
description 'https://github.com/thelindat/hsn-inventory'
version '1.5.4'

client_scripts {
	'config.lua',
	'client.lua'
}

server_scripts {
	'config.lua',
	'server.lua'
}

ui_page "html/index.html"
files {
	'html/index.html',
	'html/script.js',
	'html/style.css',
	'html/reset.css',
	'html/images/*.png',
}

exports {
	'OpenStash',
	'openTargetInventory'
}

server_exports {
	'removeItem',
	'addItem',
	'getItemCount',
	'getItem',
	'canCarryItem',
	'useItem'
}

**Comment by thelindat** [comment]
Hadn't put up my version of fxmanifest so it was missing. Added.
