### ISSUE TITLE
Please make ped can move when reload ammo

### ISSUE THREAD

**Issue by SursdeyEdu** [thelindat/hsn-inventory#27]
When reload ammo the ped suddenly freeze a few second. Thank for developing this advanced inventory

**Comment by thelindat** [comment]
The ped standing in place for a moment is due to cancelling the ped tasks, which is necessary to prevent the weapon from being unequipped the moment it runs out of ammo.

I've yet to find a way to prevent unequipping without cancelling tasks.

**Comment by sahtiyan** [comment]
https://docs.fivem.net/natives/?_0x20AE33F3AC9C0033
