### ISSUE TITLE
Evidence Issue

### ISSUE THREAD

**Issue by GrizzlyRP** [thelindat/hsn-inventory#29]
Not sure if it is just myself or not, but when I do /evidence 1 or any number, it opens then instantly closes. Does not let you move mouse, or drag anything into it.

**Comment by thelindat** [comment]
Stand closer to the evidence coords. Serverside checks you are within 5 units from the coords to allow opening, but client closes inventory if you're over 1 unit.

**Comment by thelindat** [comment]
Updated distance checks to 2 units on server and client (1 for other players)

**Comment by GrizzlyRP** [comment]
Cheers, I'll test it :)
